### ISSUE TITLE
gopherpen: firefox warns of slow code execution due to js Prototype mutation

### ISSUE THREAD

**Issue by glycerine** [gopherjs/gopherpen#1]
Firefox 41.0.1 on OSX 10.9.5. gopherpen built with go1.5.1.

I'm trying out gopherpen. I added a little text to the assets/index.html.tmpl, then built it with `go build -tags=dev`. When I run it, the firefox dev console reports the following alarming warning, before (or after, depending on the run), the text "Script is working!"

"mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create"

See attached screenshot.

![mutating-prototype-firefox-41 0 1-warning-screenshot](https://cloud.githubusercontent.com/assets/445247/10270588/daffae66-6aaa-11e5-9280-341daaea46e3.png)

It appears that gopherjs is modifying the javascript Prototype, and this may have a serious performance penalty.

**Comment by glycerine** [comment]
File issue https://github.com/gopherjs/gopherjs/issues/317 on gopherjs in case the issue is really there.

**Comment by dmitshur** [comment]
I think this issue is in `gopherjs` indeed. The [script](https://github.com/gopherjs/gopherpen/blob/master/assets/script/main.go) that is being compiled is extremely simple:

``` Go
// +build js

package main

func main() {
    println("Script is working!")
}
```

I can try to reproduce the error by using latest `gopherjs` directly to build that Go code and see if Firefox 41+ displays the same warning.

**Comment by neelance** [comment]
I'm debugging it right now. ;-)

**Comment by dmitshur** [comment]
I've verified this is an issue in GopherJS and nothing gopherpen-specific, so I'll close it here. Let's move discussion to https://github.com/gopherjs/gopherjs/issues/317.
