### ISSUE TITLE
Try to improve example script initial code.

### ISSUE THREAD

**Issue by dmitshur** [gopherjs/gopherpen#3]
Currently, the script in `index.html.tmpl` executes before the body, so trying to do any DOM operations in it will fail unless user delays them until DOMContentLoad event or equivalent.

We should arrange it so it script runs after body exists to make it friendlier.

**Comment by neelance** [comment]
Alternatively you could suggest the flicker-free way of setting the body:

``` go
body := js.Global.Get("document").Call("createElement", "body")
[modify body]
js.Global.Get("document").Set("body", body)
```

**Comment by neelance** [comment]
But then you could not have elements in the body of in the `index.html.tmpl` file, so it's probably not a good solution here.

**Comment by dmitshur** [comment]
I think it's better to go with one of the 2 solutions I proposed [here](https://gist.github.com/shurcooL/9004ed3bf2bbb62e68bd#gistcomment-1590462).

**Comment by neelance** [comment]
Yeah. For a simple example code I'd just move the script tag.

**Comment by neelance** [comment]
LGTM

**Comment by dmitshur** [comment]
> LGTM

This is an issue. @neelance, did you mean to post that comment in PR #2?

**Comment by neelance** [comment]
Hehe, yeah.
