### ISSUE TITLE
go generate blowing up

### ISSUE THREAD

**Issue by joeblew99** [gopherjs/gopherpen#4]
not sure if i am doing this right...

i pulled the code as stated in the readme, and have this:

```

MacBook-Pro:gopherjs apple$ ls -l
total 0
drwxr-xr-x  15 apple  staff  510 Nov  6 11:24 gopherjs
drwxr-xr-x  10 apple  staff  340 Nov 17 10:48 gopherpen


```

then from gopherpen dir, i run go generate, and get:

```

MacBook-Pro:gopherpen apple$ go generate
../../shurcooL/go/gopherjs_http/main.go:16:2: cannot find package "github.com/shurcooL/gopherjslib" in any of:
    /usr/local/go/src/github.com/shurcooL/gopherjslib (from $GOROOT)
    /Users/apple/workspace/go/src/github.com/shurcooL/gopherjslib (from $GOPATH)
assets_prod.go:3: running "go": exit status 1
MacBook-Pro:gopherpen apple$ 



```

**Comment by joeblew99** [comment]
ok, i just had to grab the dependency. You might want to update readme or the code imports.

```


github.com/shurcooL/gopherjslib


```

then go generate form the gopherpen works.

```

MacBook-Pro:gopherpen apple$ go get github.com/shurcooL/gopherjslib
MacBook-Pro:gopherpen apple$ go generate
REBUILDING SOURCE for: script.js using [main.go]
goReadersToJs taken: 1.090371389s


```

**Comment by dmitshur** [comment]
I think this is a legitimate issue, thanks for reporting.

My intention was for this step `go get -u -d -tags=generate github.com/gopherjs/gopherpen/...` to fetch that dependency, but I see now that it wouldn't.

**Comment by dmitshur** [comment]
I think the only correct/reliable way of resolving this is to add a `go get -u -d -tags=dev github.com/gopherjs/gopherpen/...` step. That will fetch all additional dependencies of development mode.

I'll fix it now.

**Comment by dmitshur** [comment]
I've confirmed this valid issue is now resolved. Starting with an empty GOPATH workspace, following the updated installation directions in the README now works correctly.

Thanks again for reporting it @joeblew99!
