### ISSUE TITLE
Gopherjs 1.9-1 and go 1.9.1 on windows

### ISSUE THREAD

**Issue by linkerlin** [gopherjs/gopherpen#9]
C:\Users\Administrator\go\src\github.com\gopherjs\gopherpen\assets\script (master)
λ gopherjs build main.go
..\..\..\..\..\..\..\..\..\Go\src\internal\poll\fd_windows.go:367:22: invalid operation: fd.pd (variable of type pollDesc) has no field or method runtimeCtx
..\..\..\..\..\..\..\..\..\Go\src\internal\poll\fd_windows.go:368:22: invalid operation: fd.pd (variable of type pollDesc) has no field or method runtimeCtx
..\..\..\..\..\..\..\..\..\Go\src\internal\poll\fd_windows.go:157:5: invalid operation: o.fd.pd (variable of type pollDesc) has no field or method runtimeCtx

**Comment by dmitshur** [comment]
This is related to https://github.com/gopherjs/gopherjs/issues/688, GopherJS does not support compiling natively on Windows at this time.
